### ISSUE TITLE
bug: Setting transparency = false still has transparency

### ISSUE THREAD

**Issue by mizlan** [rose-pine/neovim#243] opened 2024-02-15 20:01 UTC
### Neovim version (nvim -v)

v0.10.0-dev-1999+g6f6abd8c0

### Terminal / multiplexer

Neovide

### Describe the bug

Seems like blend is still used when transparency is disabled

### Repro

```Lua
require('rose-pine').setup({
        dark_variant = 'moon',
        disable_italics = true,
        styles = {
          bold = true,
          italic = true,
          transparency = false,
        },
...
```

**Comment by mvllow** [comment] 2024-02-15 21:01
Could you elaborate on what blend you mean? If your window is transparent that's unrelated. Screenshots would be helpful :)

**Comment by mizlan** [comment] 2024-02-16 17:43
Sure, sorry, was in a hurry when I posted the original issue. I use Neovide, which currently doesn't render blend properly, because it will bleed the desktop wallpaper through. Here is the link issue, which has a screenshot: https://github.com/neovide/neovide/issues/2327 I tried disabling blend in the colorscheme with

```
        highlight_groups = {
...
          GitSignsAdd                = { fg = "#bacfc4" },
          GitSignsChange             = { fg = "#e6d2c1" },
          GitSignsDelete             = { fg = "#dbb6b4" },
...
```
and with both 0 and 100 values, but it doesnt work. Also, like i said in the original comment, disabling `transparency` doesnt seem to work either.

**Comment by mvllow** [comment] 2024-02-16 19:47
Oh I see, appreciate the extra info. This could definitely be improved from our side once I have some time but until then:

```lua
highlight_groups = {
          GitSignsAdd                = { fg = "#bacfc4", inherit = false },
          GitSignsChange             = { fg = "#e6d2c1", inherit = false },
          GitSignsDelete             = { fg = "#dbb6b4", inherit = false },
}
```

By default, these groups are being merged with the groups from the theme. Setting `inherit = false` should fix your issue for those groups at least. Note, you may need to update the background as well.

**Comment by mizlan** [comment] 2024-02-27 17:57
Seems that it's still occurring

**Comment by mvllow** [comment] 2024-04-09 18:08
It looks like Neovide might handle this via https://github.com/neovide/neovide/issues/2471

After re-reading the initial issue you linked, though, I realised that we are using the `blend` property but never intended it to actually blend via Neovim's API—we take the blend value and apply our own logic to have a colour that looks blended. In short, adding `blend = 1` or `blend = 0` (not able to test at the moment) to the groups mentioned above may fix this.

**Comment by mizlan** [comment] 2024-05-05 22:27
I don't think either works

**Comment by shivajreddy** [comment] 2024-06-07 02:08
Yup, transparency = true is  not working. other themes do have working transparency

**Comment by mvllow** [comment] 2024-06-07 02:12
@shivajreddy that sounds like another issue since this issue is about `false` not working. What are you seeing to say `true` is also not working?

**Comment by shivajreddy** [comment] 2024-06-20 10:44
Setting the transparency to true does nothing, I checked with catppuccin theme and transparency works with my current terminal config, but if I use rose pine theme the transparency is always off.

`  {
    "rose-pine/neovim",
    lazy = false,
    name = "rose-pine",
    variant = "main", -- auto, main, moon, or dawn

    dark_variant = "main", -- main, moon, or dawn
    dim_inactive_windows = false,
    extend_background_behind_borders = true,

    enable = {
      terminal = true,
      legacy_highlights = true,
      migrations = true, -- Handle deprecated options automatically
    },

    styles = {
      bold = true,
      italic = false,
      transparency = true,
    },

    groups = {
      border = "muted",
      link = "iris",
      panel = "surface",

      error = "love",
      hint = "iris",
      info = "foam",
      note = "pine",
      todo = "rose",
      warn = "gold",

      git_add = "foam",
      git_change = "rose",
      git_delete = "love",
      git_dirty = "rose",
      git_ignore = "muted",
      git_merge = "iris",
      git_rename = "pine",
      git_stage = "iris",
      git_text = "rose",
      git_untracked = "subtle",

      h1 = "iris",
      h2 = "foam",
      h3 = "rose",
      h4 = "gold",
      h5 = "pine",
      h6 = "foam",
    },

    highlight_groups = {
      Comment = { fg = "foam" },
      VertSplit = { fg = "muted", bg = "muted" },
      GitSignsAdd = { fg = "#bacfc4", inherit = false },
      GitSignsChange = { fg = "#e6d2c1", inherit = false },
      GitSignsDelete = { fg = "#dbb6b4", inherit = false },
    },
  },

  -- Configure LazyVim to load the colorscheme
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "rose-pine",
      -- colorscheme = "catppuccin",
    },
  },
`

**Comment by bhuvneshuchiha** [comment] 2024-06-20 18:25
Did anyone face issue that with disable_background set to true, it still gives the rose-pine theme background to nvim-treesitter-context

**Comment by sjclayton** [comment] 2024-07-21 18:42
@bhuvneshuchiha 

I can confirm this on my end.

**Comment by sjclayton** [comment] 2024-07-22 10:39
@shivajreddy

Transparency is working just fine on my end... Can you try something for me?

Set `extend_background_behind_borders = false` while you have transparency on and let me know what happens.

**Comment by bhuvneshuchiha** [comment] 2024-07-22 11:44
> @bhuvneshuchiha
> 
> I can confirm this on my end.
> 
> Will be fixed by #294. 😄

https://github.com/rose-pine/neovim/pull/294 -- Please check this out mate

**Comment by bhuvneshuchiha** [comment] 2024-07-22 11:44
Have added a follow up here https://github.com/rose-pine/neovim/pull/294

**Comment by mvllow** [comment] 2024-07-24 00:00
I believe this is resolved :)

**Closed by mvllow** 2024-07-24 00:00 UTC
Labels: bug
