### ISSUE TITLE
Weird display when installing with vim-plug

### ISSUE THREAD

**Issue by Jerome1337** [rose-pine/neovim#85] opened 2022-07-10 14:21 UTC
I'm using vim-plug to install every nvim plugins.

I installed the color scheme like this inside my `.vimrc`

```vim
call plug#begin(stdpath('data') . '/plugged')
	...
	Plug 'rose-pine/neovim', {'as': 'rose-pine', 'tag': 'v1.*'}
call plug#end()

colorscheme rose-pine
```

Rose-pine is correctly installed but there is a weird black background and not the correct colors displayed.

<img width="931" alt="Screenshot 2022-07-10 at 4 17 01 PM" src="https://user-images.githubusercontent.com/7968649/178148810-798a78b9-b14a-4a01-a255-69a709d0ed44.png">

Did I miss something ?

**Comment by mvllow** [comment] 2022-07-10 14:49
If you're using neovim, which version? For regular vim it may not be working due to many parts being in lua / possibly neovim specific. If that's the case, I'd love to improve the experience on regular vim.

Otherwise, `termguicolors` may not be set correctly.

Happy to give more detailed steps if needed for anything 😌

**Comment by Jerome1337** [comment] 2022-07-10 15:59
@mvllow Im using neovim `0.7.2`

```
~ ❯ nvim --version
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.2/share/nvim"

Run :checkhealth for more info
```

My `vim.init` contains `set termguicolors` and my terminal emulator (Alacritty) has `xterm-256color` enabled

**Comment by mvllow** [comment] 2022-07-10 18:13
Hmm can't seem to reproduce with a fresh install of neovim and alacritty, with only the following in `init.vim`:

```viml
call plug#begin('~/.vim/plugged')
	Plug 'rose-pine/neovim'
call plug#end()

colorscheme rose-pine
```

<img width="705" alt="Screenshot 2022-07-10 at 14 11 32" src="https://user-images.githubusercontent.com/1474821/178156941-32c6299e-1549-4388-a89f-ed52be7abdf5.png">

**Comment by Jerome1337** [comment] 2022-07-11 08:24
Yes, this is a bit weird, I configured my Alacritty with rose-pine theme and this seems to break the nvim colorscheme.
I need to disable background inside nvim rose-pine config to make it work correctly.

Without disabled background:
<img width="801" alt="Screenshot 2022-07-11 at 10 22 37 AM" src="https://user-images.githubusercontent.com/7968649/178220825-72b49241-f9a8-4102-a0a6-077f3c83a107.png">

With disabled background:
<img width="802" alt="Screenshot 2022-07-11 at 10 22 56 AM" src="https://user-images.githubusercontent.com/7968649/178220844-af396d23-e45d-4ae1-9d96-311efe677ecf.png">

**Comment by mvllow** [comment] 2022-07-21 15:34
I'm curious if everything looks fine if using kitty + rosé pine if you're able/willing to try that. If that does work we can narrow it down to an issue with alacritty or our theme for alacritty.

**Comment by Jerome1337** [comment] 2022-07-25 08:53
I did the test with Kitty, the colors a the same as Alacritty (with the disabled background). NeoVim config are the same on both terminal emulator.

Alacritty:
<img width="623" alt="Screenshot 2022-07-25 at 10 49 59 AM" src="https://user-images.githubusercontent.com/7968649/180737391-4a7154e5-c991-49a2-ab98-51321c96eabf.png">

Kitty:
<img width="647" alt="Screenshot 2022-07-25 at 10 49 54 AM" src="https://user-images.githubusercontent.com/7968649/180737450-d1b6ddb4-7129-48bf-9662-add14b6fdb4b.png">

I don't know if there is a problem but the theme on Alacritty -> NeoVim with the disabled background seems fine

**Comment by mvllow** [comment] 2023-01-08 23:53
Closing as I am unable to reproduce. Happy to revisit if the problem persists and can be reproduced.

**Closed by mvllow** 2023-01-08 23:53 UTC

**Comment by mvllow** [comment] 2023-05-21 19:47
Ah! I wasn't too familiar with tmux at the time of this issue being created and after this issue arose again in our Discord, I realised tmux was being used here. I was able to reproduce and fix via the following:

```yaml
# ~/.config/tmux/tmux.conf
set-option -g default-terminal        'screen-256color'
set-option -g terminal-overrides      ',xterm-256color:RGB'
```

```sh
# Start tmux with explicit TERM
TERM=xterm-256color tmux
```

Please note, I am not 100% sure which parts are doing what but this specific combination solved the problem for me. Would love if someone knows how to simplify what I'm trying to accomplish here :)

Quite the delay, but hope this helps someone!
